//
//  GreetingInteractor.swift
//  CleanSwiftGreeting
//
//  Created by Alexey Gaidykov on 22.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingBusinessLogic {
    func doSomething(request: Greeting.Something.Request)
}

protocol GreetingDataStore {
    
}

class GreetingInteractor: GreetingBusinessLogic, GreetingDataStore {
    
    var presenter: GreetingPresentationLogic?
    var worker: GreetingWorker?
    
    func doSomething(request: Greeting.Something.Request) {
        worker = GreetingWorker()
        worker?.doSomeWork()
        
        let response = Greeting.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
