//
//  GreetingPresenter.swift
//  CleanSwiftGreeting
//
//  Created by Alexey Gaidykov on 22.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol GreetingPresentationLogic {
    func presentGreeting(response: GreetingResponse)
}

class GreetingPresenter: GreetingPresentationLogic {
    
    weak var viewController: GreetingDisplayLogic?
    
    func presentGreeting(response: GreetingResponse) {
        let greeting = "Hello \(response.name) \(response.surname)!"
        let viewModel = GreetingViewModel(greeting: greeting)
        viewController?.displayGreeting(viewModel: viewModel)
    }
}
